### ISSUE TITLE
Undeclared dependencies

### ISSUE THREAD

**Issue by natevw** [kanso/couchtypes#7]
When pushing an app defined like this:

```
{
    "name": "---",
    "version": "0.1.0",
    "description": "---",
    "load": "api",
    "modules": ["api.js"],
    "dependencies": {
        "modules": null,
        "properties": null,
        "couchtypes": null
    }
}
```

I get an error because the widgets component (which I'm not sure I'll even use — mostly needing help validating documents in a backend API) doesn't have the dependencies it needs:

```
Reading dependency tree...
loading .
preprocessor modules/add
preprocessor properties/queue
loading packages/modules
loading packages/properties
loading packages/couchtypes
loading packages/underscore
loading packages/db
loading packages/sanitize
loading packages/events
postprocessor modules/attachment
postprocessor properties/load
Error: Error when running postprocessor: "properties/load"
Error: Error loading: /Users/natevw/Desktop/Clients/Inquirium/readi-sensemaker-prototype/backend/packages/couchtypes/couchtypes/widgets.core.js
Could not require module: session (from: couchtypes/widgets.core) - Module not found
    at /Users/natevw/Desktop/Clients/Inquirium/readi-sensemaker-prototype/backend/packages/properties/node_modules/kanso-utils/modules.js:213:19
    at Array.reduce (native)
    at /Users/natevw/Desktop/Clients/Inquirium/readi-sensemaker-prototype/backend/packages/properties/node_modules/kanso-utils/modules.js:211:25
    at /Users/natevw/Desktop/Clients/Inquirium/readi-sensemaker-prototype/backend/packages/properties/node_modules/kanso-utils/node_modules/async/lib/async.js:540:23
    at /Users/natevw/Desktop/Clients/Inquirium/readi-sensemaker-prototype/backend/packages/couchtypes/couchtypes/widgets.core.js:15:15
    at /Users/natevw/Desktop/Clients/Inquirium/readi-sensemaker-prototype/backend/packages/properties/node_modules/kanso-utils/modules.js:277:47
    at /Users/natevw/Desktop/Clients/Inquirium/readi-sensemaker-prototype/backend/packages/properties/node_modules/kanso-utils/node_modules/async/lib/async.js:540:23
    at /Users/natevw/Desktop/Clients/Inquirium/readi-sensemaker-prototype/backend/packages/couchtypes/couchtypes/widgets.js:18:24
    at Object.<anonymous> (/Users/natevw/Desktop/Clients/Inquirium/readi-sensemaker-prototype/backend/packages/underscore/underscore.js:117:25)
    at Object.<anonymous> (/Users/natevw/Desktop/Clients/Inquirium/readi-sensemaker-prototype/backend/packages/underscore/underscore.js:79:34)
Failed
```

Am I using trying to use the couchtypes package wrongly?

**Comment by natevw** [comment]
The workaround I found was to add three new packages to my own kanso.json:

```
{
    "name": "---",
    "version": "0.1.0",
    "description": "---",
    "load": "api",
    "modules": ["api.js"],
    "dependencies": {
        "modules": null,
        "properties": null,
        "couchtypes": null,

        "session": null,
        "querystring": null,
        "settings": null
    }
}
```

So I suspect the issue is indeed that this package is simply missing declarations of its own dependencies on the session/querystring/settings packages.
